<?php

namespace Distrital\CecadBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GrupoInvestigacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupoInvestigacionRepository extends EntityRepository
{
}
