<?php

namespace Distrital\CecadBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InvestigadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvestigadorRepository extends EntityRepository
{
}
