parameters:
     ide_tools.twig.asset_exists_extension.class: IDE\ToolsBundle\Twig\Extension\AssetExistsExtension
     ide_tools.twig.numeros_extension.class: IDE\ToolsBundle\Twig\Extension\NumerosExtension
     ide_tools.twig.forms_extension.class: IDE\ToolsBundle\Twig\Extension\FormsExtension
     ide_tools.twig.visualizacion_extension.class: IDE\ToolsBundle\Twig\Extension\VisualizacionExtension

services:
    ide_tools.twig.asset_exists_extension:
        class: '%ide_tools.twig.asset_exists_extension.class%'
        arguments: ['@kernel']
        tags:
          - { name: twig.extension }
          
    ide_tools.twig.numeros_extension:
        class: '%ide_tools.twig.numeros_extension.class%'
        arguments: ['@kernel']
        tags:
          - { name: twig.extension }

    ide_tools.twig.forms_extension:
        class: '%ide_tools.twig.forms_extension.class%'
        arguments: ['@kernel']
        tags:
          - { name: twig.extension }

    ide_tools.twig.visualizacion_extension:
        class: '%ide_tools.twig.visualizacion_extension.class%'
        arguments: ['@kernel']
        tags:
          - { name: twig.extension }



