parameters:
#    distrital_cecad.example.class: Distrital\CecadBundle\Example

services:
#    distrital_cecad.example:
#        class: %distrital_cecad.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
